### ISSUE TITLE
Does util.old always reliable when other 3rd party browsers in those platform list?

### ISSUE THREAD

**Issue by Jinjiang** [viljamis/feature.js#28] opened 2016-01-22 15:50 UTC
For example UC Browser in Android 2.3 which supports css transform
I don't have any Android 2.x device but I guess feature.js may not work right in that situation.

Thx

**Comment by meowsus** [comment] 2019-05-13 18:22
Hey @Jinjiang, I'm not following what you're saying here. Since this issue is old I'm going to close it, but if you still need action on this issue, please feel free to reopen with steps to reproduce what you're describing. Thanks!

**Closed by meowsus** 2019-05-13 18:22 UTC
